version: '3'
services:
  test:
    image: reacraft/prod
    container_name: reacraft-test
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    entrypoint:
      ['/bin/sh', '-c', 'node dist/server/server.js & sleep 10; npm run test']
    env_file:
      - .env
    environment:
      - PROJECT_ROOT=/usr/src/app
