version: '3'
services:
  test:
    image: reacraft/prod
    container_name: reacraft-test
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    entrypoint:
      entrypoint: ['/bin/sh', '-c', 'echo Hello World']
    env_file:
      - .env
    environment:
      - PROJECT_ROOT=/usr/src/app
