name: build-tests
on:
  pull_request:
    branches:
      - dev
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    env:
      PG_URI: ${{ secrets.PG_URI }}
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PROJECT_ROOT: /usr/src/app
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit
